import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/app/component/Navbar'
import Footer from '@/app/component/Footer'
import {Toaster} from 'sonner';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en" className='overflow-x-hidden'>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Toaster richColors />
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  )
}
